name: foodrecog
description: "A new Flutter project about food recognition. Dicoding course Flutter Machine Learning. July 2026."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  image_picker: ^1.2.3
  image_cropper: ^12.2.1
  http: ^1.6.0
  tflite_flutter: ^0.12.1
  image: ^4.9.1
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.1
  firebase_core: ^4.11.0
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

